In [2]:
import numpy as np

a=np.random.randn(5)
print(a)

[1.23888954 0.17166871 0.63685096 1.27930346 1.07803225]


In [4]:
a.shape

(5,)

In [5]:
a.T

array([1.23888954, 0.17166871, 0.63685096, 1.27930346, 1.07803225])

In [6]:
#So this is a rannk 1 numpy array and its not a (5,1) matrix hence the tanspose returns the same result 
#instead if we had initialized a as a=np.random.randn(5,1) this would have returned a (5,1) matrix

In [8]:
a1=np.random.randn(5,1)
print(a1)

[[ 1.11169129]
 [-1.21451092]
 [ 0.43370742]
 [ 0.26186224]
 [-0.06516159]]


In [9]:
a1.T

array([[ 1.11169129, -1.21451092,  0.43370742,  0.26186224, -0.06516159]])